### ISSUE TITLE
Available weight release schedule?

### ISSUE THREAD

**Issue by kimtaehyeong** [JackAILab/ConsistentID#1]
Thank you for your good research.
When will the model be released?
Thank you.

**Comment by JackAILab** [comment]
> Thank you for your good research. When will the model be released? Thank you.

Models and demos will be hosted on huggingface. We are uploading the private cloud disk and it is expected to be released later today, please wait patiently~

**Comment by kimtaehyeong** [comment]
Thank you so much!
