### ISSUE TITLE
Can it support character ID in 2D anime style?

### ISSUE THREAD

**Issue by songispm** [JackAILab/ConsistentID#11]
I tried the demo, but it does not support 2D anime style images for now.

**Comment by songispm** [comment]
the source image is 2D anime style

**Comment by songispm** [comment]
keep the character consistency style

**Comment by JackAILab** [comment]
<img width="1237" alt="image" src="https://github.com/JackAILab/ConsistentID/assets/112920087/9d2049a4-05c9-42dd-8679-533a92194015">

Can you provide the image you entered and the prompt you used?
Something like this makes it easier to check~

**Comment by JackAILab** [comment]
> I tried the demo, but it does not support 2D anime style images for now.

For stylized functionality, you can refer to [issue#7](https://github.com/JackAILab/ConsistentID/issues/7). Provide stylized prompts, or use lora to assist the model in generating the desired stylization.

**Comment by songispm** [comment]
@JackAILab  need keep the style same, it is not same style.

<img width="1512" alt="image" src="https://github.com/JackAILab/ConsistentID/assets/38745323/69a7cdfd-84c4-4694-b3ad-f6b687fc67c5">

![test2-1](https://github.com/JackAILab/ConsistentID/assets/38745323/4c68f8b3-b317-4323-aec8-cbafb4d79063)

I will try more prompt words.

**Comment by songispm** [comment]
<img width="1527" alt="image" src="https://github.com/JackAILab/ConsistentID/assets/38745323/63941fc8-5ba8-4081-91c4-790b2080bb51">

still...

**Comment by JackAILab** [comment]
> <img alt="image" width="1527" src="https://private-user-images.githubusercontent.com/38745323/326874916-63941fc8-5ba8-4081-91c4-790b2080bb51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTEyNzYsIm5iZiI6MTcxNDQ5MDk3NiwicGF0aCI6Ii8zODc0NTMyMy8zMjY4NzQ5MTYtNjM5NDFmYzgtNWJhOC00MDgxLTkxYzQtNzkwYjIwODBiYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1MjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNmJlZWE5ZDhkYjBmNGU3ZDkzOTRiNDhhNjMzODFiZmI3MmFhMDhhY2ZlZWZjYTU5YmQ4ZjllMjc1MTU2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwAiK9SPWTk9CzuQ1uakXg9RMy9WV7GYnxjgw33deR8">
> still...

I understand what you mean. Currently, our base model is using SG161222/Realistic_Vision_V6.0_B1_noVAE. This is a realistic style base model, and its main purpose is to maintain the consistency of the facial features.

For stylization, you can try changing the base model or using LORA (this is an experimental feature, refer to ConsistentID
/infer.py) to achieve the effect of animate.

If you have any latest progress, you are welcome to reopen the issue and PR.
