### ISSUE TITLE
Example from paper

### ISSUE THREAD

**Issue by stqwzr** [JackAILab/ConsistentID#12]
Hello, I want to reproduce the examples from the paper. As mentioned in paper do you use basic sd1.5 or some another checkpoints of sd1.5? Thank you for sharing this awesome work!

**Comment by JackAILab** [comment]
> Hello, I want to reproduce the examples from the paper. As mentioned in paper do you use basic sd1.5 or some another checkpoints of sd1.5? Thank you for sharing this awesome work!

For training we are using runwayml/stable-diffusion-v1-5 and for inference we are using SG161222/Realistic_Vision_V6.0_B1_noVAE. More detailed configuration can be found in ConsistentID/utils.py.

If you have any other questions, please feel free to open this issue again.
