### ISSUE TITLE
fyi - inference errors / for the default model it doesn't seem to have safetensor -

### ISSUE THREAD

**Issue by johndpope** [JackAILab/ConsistentID#18]
```python
# TODO import base SD model and pretrained ConsistentID model
device = "cuda"
base_model_path = "SG161222/Realistic_Vision_V6.0_B1_noVAE"
consistentID_path = "./ConsistentID_model_facemask_pretrain_50w" # pretrained ConsistentID model
# "philz1337/epicrealism" # 
# Gets the absolute path of the current script
script_directory = os.path.dirname(os.path.realpath(__file__))

### Load base model
pipe = ConsistentIDStableDiffusionPipeline.from_pretrained(
    base_model_path, 
    torch_dtype=torch.float16, 
    use_safetensors=False
).to(device)


```

safety_checker/model.safetensors not found
Traceback (most recent call last):
  File "/media/oem/12TB/ConsistentID/infer.py", line 18, in <module>
    pipe = ConsistentIDStableDiffusionPipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/ani/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1078, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/ani/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1775, in download
    raise EnvironmentError(
OSError: Could not find the necessary `safetensors` weights in {'safety_checker/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'unet/diffusion_pytorch_model.bin', 'vae/diffusion_pytorch_model.bin'} (variant=None)

Traceback (most recent call last):
  File "/media/oem/12TB/ConsistentID/infer.py", line 18, in <module>
    pipe = ConsistentIDStableDiffusionPipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/ani/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1090, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/ani/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1708, in download
    deprecate("no variant default", "0.24.0", deprecation_message, standard_warn=False)
  File "/home/oem/miniconda3/envs/ani/lib/python3.11/site-packages/diffusers/utils/deprecation_utils.py", line 18, in deprecate
    raise ValueError(
ValueError: The deprecation tuple ('no variant default', '0.24.0', "You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.The default model files: {'safety_checker/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'vae/diffusion_pytorch_model.bin', 'unet/diffusion_pytorch_model.bin'} will be loaded instead. Make sure to not load from `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error in v0.24.0 as defaulting to non-variantmodeling files is deprecated.") should be removed since diffusers' version 0.24.0 is >= 0.24.0

**Comment by johndpope** [comment]
Also there's no BiSeNet_pretrained_for_ConsistentID.pth - mentioned anywhere - could not find on huggingface - 

I do see this 
BiSeNet_pretrained_for_ConsistentID.bin

code is saying 
        self.bise_net_cp='./models/BiSeNet_pretrained_for_ConsistentID.pth' # Import BiSeNet model

**Comment by stqwzr** [comment]
@johndpope Hi, i downloaded the weigths from https://huggingface.co/JackAILab/ConsistentID/tree/main
 model and this part i change from
`self.bise_net_cp='./models/BiSeNet_pretrained_for_ConsistentID.pth' # Import BiSeNet`
to
`self.bise_net_cp='./models/face_parsing.pth' `

**Comment by wing158** [comment]
您好，base_model_path = "SG161222/Realistic_Vision_V6.0_B1_noVAE"
如项目/root/ConsistentID,需要git clone  https://huggingface.co/SG161222/Realistic_Vision_V6.0_B1_noVAE 下载到/root/ConsistentID/SG161222/Realistic_Vision_V6.0_B1_noVAE 目录下？

还是说  {'safety_checker/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'vae/diffusion_pytorch_model.bin', 'unet/diffusion_pytorch_model.bin'} 也需要下载到/root/ConsistentID具体那几个目录下，可否提示下？
