### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)

### ISSUE THREAD

**Issue by Koaxz** [JackAILab/ConsistentID#19]
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0

**Comment by JackAILab** [comment]
> ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none) ERROR: No matching distribution found for triton==2.0.0

You can try not specifying the triton version to see if it can run smoothly. The current requirement.txt has been re-verified and can be successfully built. If there are any problems with the environment setup, you are welcome to open it again.
