### ISSUE TITLE
Dataset Training 

### ISSUE THREAD

**Issue by hungho77** [JackAILab/ConsistentID#26]
If ConsistentID can train with personal data for a person. Is it better than training with a large group of people?

**Comment by zArche** [comment]
我也有相同的疑问，并且如何制作模板呢？比如我想制作生成证件照之类的模板

**Comment by JackAILab** [comment]
> If ConsistentID can train with personal data for a person. Is it better than training with a large group of people?

Using a single image can ensure sufficient ID consistency. Training on a set of character images does not significantly improve ID consistency. However, using multiple character ID data for training and testing can improve ID diversity to a certain extent (refer to [Photomaker](https://github.com/TencentARC/PhotoMaker)).

The multi-ID version of our training will be released soon, so stay tuned ~

**Comment by JackAILab** [comment]
> 我也有相同的疑问，并且如何制作模板呢？比如我想制作生成证件照之类的模板

We are about to release a ConsistentID style version to meet different styles of personalization. Of course, you can also refer to [issue7](https://github.com/JackAILab/ConsistentID/issues/7) and [issue11](https://github.com/JackAILab/ConsistentID/issues/11) to design the template prompt yourself.
