### ISSUE TITLE
BiSeNet model weight?

### ISSUE THREAD

**Issue by kimtaehyeong** [JackAILab/ConsistentID#3]
Looking for BiSeNet weight what weights did you use?

**Comment by JackAILab** [comment]
> Looking for BiSeNet weight what weights did you use?

The weight we use can be found at [face_parsing](https://drive.google.com/open?id=154JgKpzCPW82qINcVieuPH3fZ2e0P812), provided by the [face-parsing.PyTorch](https://github.com/zllrunning/face-parsing.PyTorch), thanks~
