### ISSUE TITLE
There is a missing C in filename.

### ISSUE THREAD

**Issue by levicn** [JackAILab/ConsistentID#32]
from huggingface_hub import hf_hub_download
ConsistentID_path = hf_hub_download(repo_id="JackAILab/ConsistentID", filename="onsistentID-v1.bin", repo_type="model")

Should be filename="ConsistentID-v1.bin"

**Comment by JackAILab** [comment]
> from huggingface_hub import hf_hub_download ConsistentID_path = hf_hub_download(repo_id="JackAILab/ConsistentID", filename="onsistentID-v1.bin", repo_type="model")
> 
> Should be filename="ConsistentID-v1.bin"

Thanks, I will fix it~
