### ISSUE TITLE
ConsistentID for image inpainting with controlnet

### ISSUE THREAD

**Issue by slowwords** [JackAILab/ConsistentID#35]
Hi, I tried out the text-to-image demo you released and the results were fantastic. It's really a great work!

Moreover, I'm looking to apply ConsistentID in image inpainting task with ControlNet, and I've implemented a pipeline locally for this purpose. However, the outcomes have been less than optimistic. Do you have plans to release an inpainting pipeline that includes ControlNet? Or, would you be able to guide me on how to make the necessary adjustments?

results:
![20240522-160936](https://github.com/JackAILab/ConsistentID/assets/81546228/cd60c169-8ac5-48b8-bd3e-51412875600c)

![20240522-160941](https://github.com/JackAILab/ConsistentID/assets/81546228/0cc3d31a-391a-4945-bfd1-a7172dbcb20c)

my pipeline:
```from typing import Any, Callable, Dict, List, Optional, Union, Tuple
XXX
```

refer to [StableDIffusionControlNetInpaint_ConsistentID](https://github.com/JackAILab/ConsistentID/blob/main/pipelines/StableDIffusionControlNetInpaint_ConsistentID.py)

**Comment by ykj467422034** [comment]
> Hi, I tried out the text-to-image demo you released and the results were fantastic. It's really a great work!
> 
> Moreover, I'm looking to apply ConsistentID in image inpainting task with ControlNet, and I've implemented a pipeline locally for this purpose. However, the outcomes have been less than optimistic. Do you have plans to release an inpainting pipeline that includes ControlNet? Or, would you be able to guide me on how to make the necessary adjustments?
> 
> results: ![20240522-160936](https://private-user-images.githubusercontent.com/81546228/332714669-cd60c169-8ac5-48b8-bd3e-51412875600c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDcwNTEsIm5iZiI6MTcyNzQwNjc1MSwicGF0aCI6Ii84MTU0NjIyOC8zMzI3MTQ2NjktY2Q2MGMxNjktOGFjNS00OGI4LWJkM2UtNTE0MTI4NzU2MDBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjYzNjI3YmI5NGJlMTNlMjE4MmVhNmMzNzY3ZjY2MmE5NmI2YjViNTZjNmUwZmFkMTg2ZmQwMmZjYTliNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bCEGO7EIWF58lc2hxBTIYfz4o-gOxvCj0YEY-v1sB8I)
> 
> ![20240522-160941](https://private-user-images.githubusercontent.com/81546228/332714733-0cc3d31a-391a-4945-bfd1-a7172dbcb20c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDcwNTEsIm5iZiI6MTcyNzQwNjc1MSwicGF0aCI6Ii84MTU0NjIyOC8zMzI3MTQ3MzMtMGNjM2QzMWEtMzkxYS00OTQ1LWJmZDEtYTcxNzJkYmNiMjBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMDc0YWU2YTViNWFjMGUwNTM0MTUwY2EwY2Y4NDVlNmRkOTZjNWY4MjhlNGY1ZmQ1M2FmNzY2ZTM0ZWRkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nT1W0HCSNs9vpITi3c-KuFebegwpBoO9DreiX0nCRoQ)
> 
> my pipeline:
> 
> ```
> XXX
> ```
> 
> refer to [StableDIffusionControlNetInpaint_ConsistentID](https://github.com/JackAILab/ConsistentID/blob/main/pipelines/StableDIffusionControlNetInpaint_ConsistentID.py)

Hello I am studying face swapping and I found that the two pictures you gave have very good effects. Can I refer to your code? I tried this link https://github.com/JackAILab/ConsistentID/blob/main/pipelines/StableDIffusionControlNetInpaint_ConsistentID.pyand the effect is very poor.
