### ISSUE TITLE
GPU need

### ISSUE THREAD

**Issue by AsukaCamellia** [JackAILab/ConsistentID#38]
Can I use 4 NVIDIA 4090 GPUs to train this model？

**Comment by JackAILab** [comment]
> Can I use 4 NVIDIA 4090 GPUs to train this model？

Yes, just make sure your environment is configured correctly. For specific parameter settings, please refer to the Experiment chapter of our [paper](https://arxiv.org/abs/2404.16771).

**Comment by AsukaCamellia** [comment]
> > Can I use 4 NVIDIA 4090 GPUs to train this model？
> 
> Yes, just make sure your environment is configured correctly. For specific parameter settings, please refer to the Experiment chapter of our [paper](https://arxiv.org/abs/2404.16771).

Thanks for your reply.  When will the training data, test data, and test code be released? I would like to follow up on this wonderful work in the future.

**Comment by JackAILab** [comment]
@AsukaCamellia Permission to republish the source data has not yet been granted, but a script for the data remastering will be released this week. Some test data and evaluation code will be released later, but their priority is not high compared to other current tasks, so please wait patiently~

**Comment by JackAILab** [comment]
@AsukaCamellia [scripts](https://github.com/JackAILab/ConsistentID/blob/main/data/FGID.sh) Now, the data production instructions and scripts have been released. If you have any questions, please feel free to submit ISSUE and PR.

**Comment by AsukaCamellia** [comment]
> @AsukaCamellia [scripts](https://github.com/JackAILab/ConsistentID/blob/main/data/FGID.sh) Now, the data production instructions and scripts have been released. If you have any questions, please feel free to submit ISSUE and PR.

Thank you so much for your open-source spirit. I believe your work will become very impactful!
