### ISSUE TITLE
vqa_LLVA and vqa_LLVA_more_face_detail

### ISSUE THREAD

**Issue by gaoyixuan111** [JackAILab/ConsistentID#42]
"When I use LLAVA to generate the corresponding captions, the speed is very slow, taking about one minute to complete the vqa_LLVA and vqa_LLVA_more_face_detail descriptions for a single image."

**Comment by JackAILab** [comment]
Hi, @gaoyixuan111 The llava model is time-consuming to load. After loading, theoretically, I use one 3090 GPU and can complete the caption of a single image within 1.5 seconds.
Check your code to make sure that the model is not loaded repeatedly in a loop.

**Comment by gaoyixuan111** [comment]
@JackAILab Could you share the training time for the model on 8 V100 GPUs and provide more training details?

**Comment by JackAILab** [comment]
Hi, @gaoyixuan111 , you can refer to this [issue50](https://github.com/JackAILab/ConsistentID/issues/50)~
