### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by Hany1978** [JackAILab/ConsistentID#51]
I installed ConsistentID locally on Windows, but everytime when generation is complete I always get this error and no Image found in the output folder:
Invalid argument: 'D:\\ConsistentID\\images\\gradio_outputs\\2024-07-11 08:10:15.281688-168.jpg'

I tried to modify the app.py save image dir, but tired from trying, nothing helped
So is there any solution?

**Comment by JackAILab** [comment]
Hi, @Hany1978 , you can change this code [app_L79](https://github.com/JackAILab/ConsistentID/blob/main/app.py#L79), just specify a fixed path such as:
`images.save("./2024-07-11 08:10:15.281688-168.jpg") `

you can also refer to this [issue28](https://github.com/JackAILab/ConsistentID/issues/28)
