### ISSUE TITLE
HuggingFace gradio demo on Windows

### ISSUE THREAD

**Issue by Hany1978** [JackAILab/ConsistentID#53]
Hello
I'm trying to use the "app.py" frm the huggingface demo to get the same features of the demo page on my Windows PC, but when I execute the app.py script  and after it loads many things it gives me this error

RuntimeError: You can't move a model that has some modules offloaded to cpu, or disk

Is there any lines to edit or change to bypass this error?

**Comment by JackAILab** [comment]
hi @Hany1978  you can try to using this [file](https://github.com/JackAILab/ConsistentID/blob/main/app.py) to run, the app.py in huggingface have some special integrated functions.
