### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by zys1994** [JackAILab/ConsistentID#6]
Will the dataset including 50000 images release?

**Comment by JackAILab** [comment]
> Will the dataset including 50000 images release?

We are evaluating the possibility of re-publishing the dataset. Currently the [FFHQ](https://github.com/NVlabs/ffhq-dataset) data should be re-publishable, but we will need time to obtain permission. Once the permission is obtained, we will publish it in the warehouse in time, thank you for your patience~

However, we expect to release the detailed production code of the dataset within this week, and you can also re-create any face dataset through the code to retrain ConsistentID.

**Comment by JackAILab** [comment]
@zys1994  [scripts](https://github.com/JackAILab/ConsistentID/blob/main/data/FGID.sh) Now, the data production instructions and scripts have been released. If you have any questions, please feel free to submit ISSUE and PR.
