### ISSUE TITLE
can you explain

### ISSUE THREAD

**Issue by zachysaur** [JackAILab/ConsistentID#9]
where to put model file and data how to prepare and jason file

**Comment by JackAILab** [comment]
> where to put model file and data how to prepare and jason file

- The model can be placed anywhere, just specify the path when running the code.

- The data preprocessing method will be released as soon as possible, refer to [issue#6](https://github.com/JackAILab/ConsistentID/issues/6)

Once the data are prepared (parsing_mask, faceID, llava caption), json file structure can be found as follows:
[
    {
        "resize_IMG": "Path to resized image...",
        "parsing_mask_IMG": "...",
        "vqa_llva": "...",
        "id_embed_file_resize": "...",
    },
    ...
]
